select * from mundo; 
select * from regiao; 
select * from local ;
select * from personagem ;
select * from npc;
select * from instancia;
select * from missao ;
select * from chefe ;
select * from personagem ;
select * from pc ;
select * from fazmissao ;
select * from contem ;
select * from local ;
select * from habilidade ;
select * from possuihab ;
select * from item ;
select * from inventario ;
select * from instanciaitem ;
select * from dropa ;
select * from loja ;
select * from possuiitem ;