from .Armadura import *
from .Armamento import * 
from .Chefe import *
from .Consumivel import *
from .Contem import * 
from .Database import *
from .Dropa import * 
from .FazMissao import *
from .Habilidade import *
from .Instancia import *
from .InstanciaItem import *   
from .Inventario import * 
from .Item import * 
from .Local import * 
from .Loja import *
from .Missao import *
from .Mundo import * 
from .Npc import * 
from .Pc import * 
from .Personagem import *
from .PossuiHab import * 
from .PossuiItem import * 
from .PreRequisitoHab import * 
from .PreRequistoMissao import *
from .Regiao import * 